services:
  - type: web
    name: product-store-3d
    env: static
    buildCommand: npm run build
    publishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
